version: "3.8"
services:
  nextjs:
    build: .
    container_name: antcoders-nextjs
    restart: always
    environment:
      - NODE_ENV=production
      - VIRTUAL_HOST=antcoders.dev,www.antcoders.dev
      - LETSENCRYPT_HOST=antcoders.dev,www.antcoders.dev
      - LETSENCRYPT_EMAIL=antcoderstoken@gmail.com
    networks:
      - nginx-proxy
    expose:
      - "3000"

  nginx-proxy:
    image: nginxproxy/nginx-proxy:latest
    container_name: nginx-proxy
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /etc/nginx/certs:/etc/nginx/certs
      - /etc/nginx/vhost.d:/etc/nginx/vhost.d
      - /usr/share/nginx/html:/usr/share/nginx/html
      - /var/run/docker.sock:/tmp/docker.sock:ro
    networks:
      - nginx-proxy

  letsencrypt:
    image: nginxproxy/acme-companion:latest
    container_name: nginx-letsencrypt
    restart: always
    environment:
      - DEFAULT_EMAIL=antcoderstoken@gmail.com
      - NGINX_PROXY_CONTAINER=nginx-proxy
    volumes:
      - /etc/nginx/certs:/etc/nginx/certs
      - /var/run/docker.sock:/var/run/docker.sock:ro,z
      - /etc/acme.sh:/etc/acme.sh
    volumes_from:
      - nginx-proxy
    networks:
      - nginx-proxy

networks:
  nginx-proxy:
    external: true
