version: "3.8"
services:
  nextjs:
    build: .
    container_name: antcoders-nextjs
    restart: always
    environment:
      - NODE_ENV=production
      - VIRTUAL_HOST=antcoders.dev,www.antcoders.dev
      - LETSENCRYPT_HOST=antcoders.dev,www.antcoders.dev
      - LETSENCRYPT_EMAIL=antcoderstoken@gmail.com
    networks:
      - nginx-proxy
    expose:
      - "3000"

networks:
  nginx-proxy:
    name: nginx-proxy
    driver: bridge
