version: "3.8"
services:
  nginx-proxy:
    image: jwilder/nginx-proxy
    container_name: nginx-proxy
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ./certs:/etc/nginx/certs
      - ./vhost.d:/etc/nginx/vhost.d
      - ./html:/usr/share/nginx/html
      - ./nginx.conf:/etc/nginx/conf.d/custom.conf
    networks:
      - nginx-network

  letsencrypt:
    image: jrcs/letsencrypt-nginx-proxy-companion
    container_name: nginx-letsencrypt
    restart: always
    environment:
      - NGINX_PROXY_CONTAINER=nginx-proxy
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./certs:/etc/nginx/certs
      - ./vhost.d:/etc/nginx/vhost.d
      - ./html:/usr/share/nginx/html
    networks:
      - nginx-network

  antcoders-app:
    build: .
    container_name: antcoders-nextjs
    restart: always
    expose:
      - "3000"
    environment:
      - VIRTUAL_HOST=antcoders.dev,www.antcoders.dev
      - LETSENCRYPT_HOST=antcoders.dev,www.antcoders.dev
      - LETSENCRYPT_EMAIL=youremail@example.com
    networks:
      - nginx-network

networks:
  nginx-network:
    external: true
